name: Build latest (Android2)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
  schedule:
    # Every Sunday at 12am
    - cron: '0 0 * * 0'
concurrency:
  group: ${{ github.ref }}-android
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/saschpe/android-ndk:34-jdk17.0.8_7-ndk25.2.9519653-cmake3.22.1
    steps:
      - uses: actions/checkout@v4

      - name: Retrieve dependencies
        shell: bash
        run: |
          mkdir build-tools
          wget https://github.com/ClassiCube/rpi-compiling-stuff/raw/main/build-tools.zip
          unzip build-tools.zip -d build-tools
          chmod +x build-tools/aapt
          chmod +x build-tools/dx
          chmod +x build-tools/zipalign

      - name: Compile android builds
        shell: bash
        id: compile
        env: 
          COMMON_FLAGS: "-O1 -s -fno-stack-protector -fno-math-errno -Qn -Werror"
          DROID_FLAGS: "-fPIC -shared -fvisibility=hidden -rdynamic -funwind-tables"
          DROID_LIBS: "-lGLESv2 -lEGL -lm -landroid -llog"
        run: |
          LATEST_FLAG=-DCC_COMMIT_SHA=\"${GITHUB_SHA::9}\"
          
          DROID_FLAGS="-fPIC -shared -s -O1 -fvisibility=hidden -rdynamic -funwind-tables"
          DROID_LIBS="-lGLESv2 -lEGL -lm -landroid -llog"
          
          ROOT_DIR=$PWD
          NDK_ROOT="/opt/android-sdk-linux/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin"
          TOOLS_ROOT=$ROOT_DIR/build-tools
          SDK_ROOT="/opt/android-sdk-linux/platforms/android-34"

          cd $ROOT_DIR/src
          $NDK_ROOT/armv7a-linux-androideabi19-clang *.c $COMMON_FLAGS $DROID_FLAGS -march=armv5 -rtlib=libgcc -L $ROOT_DIR/build-tools/runtime $DROID_LIBS $LATEST_FLAG -o hc-droid-arm_16
          $NDK_ROOT/armv7a-linux-androideabi19-clang *.c $COMMON_FLAGS $DROID_FLAGS $DROID_LIBS $LATEST_FLAG -o hc-droid-arm_32
          $NDK_ROOT/aarch64-linux-android21-clang *.c $COMMON_FLAGS $DROID_FLAGS $DROID_LIBS $LATEST_FLAG -o hc-droid-arm_64
          $NDK_ROOT/i686-linux-android21-clang *.c $COMMON_FLAGS $DROID_FLAGS $DROID_LIBS $LATEST_FLAG -o hc-droid-x86_32
          $NDK_ROOT/x86_64-linux-android21-clang *.c $COMMON_FLAGS $DROID_FLAGS $DROID_LIBS $LATEST_FLAG -o hc-droid-x86_64
          
          cd $ROOT_DIR/android/app/src/main
          # copy required native libraries
          mkdir lib lib/armeabi lib/armeabi-v7a lib/arm64-v8a lib/x86 lib/x86_64
          cp $ROOT_DIR/src/hc-droid-arm_16 lib/armeabi/libharmonyclient.so
          cp $ROOT_DIR/src/hc-droid-arm_32 lib/armeabi-v7a/libharmonyclient.so
          cp $ROOT_DIR/src/hc-droid-arm_64 lib/arm64-v8a/libharmonyclient.so
          cp $ROOT_DIR/src/hc-droid-x86_32 lib/x86/libharmonyclient.so
          cp $ROOT_DIR/src/hc-droid-x86_64 lib/x86_64/libharmonyclient.so
          
          # The following commands are for manually building an .apk, see
          #  https://spin.atomicobject.com/2011/08/22/building-android-application-bundles-apks-by-hand/
          #  https://github.com/cnlohr/rawdrawandroid/blob/master/Makefile
          #  https://stackoverflow.com/questions/41132753/how-can-i-build-an-android-apk-without-gradle-on-the-command-line
          #  https://github.com/skanti/Android-Manual-Build-Command-Line/blob/master/hello-jni/Makefile
          #  https://github.com/skanti/Android-Manual-Build-Command-Line/blob/master/hello-jni/CMakeLists.txt
          
          # compile java files into multiple .class files
          cd $ROOT_DIR/android/app/src/main/java/com/classicube
          javac *.java -d $ROOT_DIR/android/app/src/main/obj -classpath $SDK_ROOT/android.jar --release 8
          
          cd $ROOT_DIR/android/app/src/main
          # get debug signing key
          echo -n "${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}" | base64 --decode > debug.keystore
          
          # compile the multiple .class files into one .dex file
          $TOOLS_ROOT/dx --dex --output=classes.dex ./obj
          # create initial .apk with packaged version of resources
          $TOOLS_ROOT/aapt package -f -M AndroidManifest.xml -S res -F hc-unsigned.apk -I $SDK_ROOT/android.jar
          # and add all the required files
          $TOOLS_ROOT/aapt add -f hc-unsigned.apk classes.dex lib/armeabi/libclassicube.so lib/armeabi-v7a/libclassicube.so lib/arm64-v8a/libclassicube.so lib/x86/libclassicube.so lib/x86_64/libharmonyclient.so
          
          # sign the apk with debug key (https://stackoverflow.com/questions/16711233/)
          # Note per https://developer.android.com/tools/zipalign
          # - if using apksigner, zipalign must be called before apksigner
          # - if using jarsigner, zipalign must be called after jarsigner
          $TOOLS_ROOT/zipalign -f 4 hc-unsigned.apk hc-signed.apk
          $TOOLS_ROOT/apksigner sign --ks debug.keystore --ks-pass pass:android hc-signed.apk
          cp hc-signed.apk $ROOT_DIR/src/hc.apk

          # old v1 only version (doesn't work properly now)
          #cp hc-unsigned.apk hc-signed.apk
          #jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass android -keypass android hc-signed.apk androiddebugkey
          # jarsigner -verbose
          # create aligned .apk file
          #$TOOLS_ROOT/zipalign -f 4 hc-signed.apk $ROOT_DIR/src/hc.apk

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile HarmonyClient android build <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'src/hc.apk'
          DEST_NAME: 'HarmonyClient.apk'

      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled HarmonyClient android build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
