name: Build latest (NDS)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-nds
  cancel-in-progress: true

jobs:
  build-DS:
    runs-on: ubuntu-latest
    container:
      image: skylyrac/blocksds:dev-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile NDS build
        id: compile
        run: |
          apt-get -y install curl
          export BLOCKSDS=/opt/blocksds/core
          export BLOCKSDSEXT=/opt/blocksds/external
          make ds


      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile HarmonyClient NDS build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
 
         
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube.nds'
          DEST_NAME: 'HarmonyClient.nds'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'build-nds/ClassiCube.elf'
          DEST_NAME: 'HarmonyClient-nds.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled HarmonyClient NDS build.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
