name: Build latest (PSP)
# trigger via either push to selected branches or on manual run
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-psp
  cancel-in-progress: true

jobs:
  build-PSP:
    runs-on: ubuntu-latest
    container:
      image: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile PSP build
        id: compile
        run: |
          apk add curl curl-dev
          export PSPSDK=$(psp-config --pspsdk-path)
          make psp
          

      - uses: ./.github/actions/notify_failure
        if: ${{ always() && steps.compile.outcome == 'failure' }}
        with:
          NOTIFY_MESSAGE: 'Failed to compile HarmonyClient PSP build! <@999409543001931788>'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
          
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'EBOOT.PBP'
          DEST_NAME: 'EBOOT.PBP'
          
      - uses: ./.github/actions/upload_build
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          SOURCE_FILE: 'ClassiCube-psp.elf'
          DEST_NAME: 'HarmonyClient-psp.elf'
          
          
      - uses: ./.github/actions/notify_success
        if: ${{ always() && steps.compile.outcome == 'success' }}
        with:
          NOTIFY_MESSAGE: 'Successfully compiled HarmonyClient PSP builds.'
          WEBHOOK_URL: '${{ secrets.WEBHOOK_URL }}'
